### ISSUE TITLE
Can't apt-get in my container

### ISSUE THREAD

**Issue by caprenter** [Blushtones/jimdave#11]
I know I probably shouldn't apt-get inside the container, (but maybe it's ok while we experiment)

Anyway, I was getting errors, once inside the container,  that the /tmp file was not writeable, so I had to 

`chmod -R 1777 /tmp` as per this answer here:

https://stackoverflow.com/a/53950173

@Plebster - I think this is just something to document?

**Comment by Plebster** [comment]
@caprenter, which container? I wonder if we've stumbled on this before with mysql... I'm assuming your /tmp is set in your volumes in docker-compose?

`chmod -R 1777 /tmp` on your host machine or within the container? I think on your host machine...

There is some nuance here with how docker looks at volumes between OSX and nix which is odd as they're both *nix based. I'm sure it is related to who the docker deamon runs as but not 100%

We did mention about changing the /tmp to /temp in docker-compose to avoid this issue with mysql, it might be prudent to make this change to all the containers that are in docker-compose file,  any thoughts?

**Comment by caprenter** [comment]
So this is in the drupal container.

Yes, /tmp is set in the docker-compose - it contains the site files tar.gz files 

I think it needs to still be called /tmp file as this is the apt-get process failing to write to /tmp file. 
I'm guessing that for us to use /temp it's just a way of not interfering with anything else that's going on?

I'm documenting it, because the other day you said you'd just apt-get update, apt-get install and it had worked. - and it didn't for me - until I did the chmod (in the container)

**Comment by Plebster** [comment]
no, this is a read/write permission issue between the host file system and the container.

the /tmp file will still exist in the container with all the correct permissions if we don't reference this in the volumes array

our current use of /tmp is just a place to hold our tar.gz... we can have this be any name we like. Also our documentation for the docker-compose usage, which I'm slow working on should have us remove the /tmp or whatever we call from the volume array once we have untarred the data and then deleted from the host file

**Comment by Plebster** [comment]
in fact there is a case where we might not need a place for our tar.gz at all, this could all be done on the host and placed in the {DRUPAL_SITE_FILES} folder prior to spinning up the containers.
