### ISSUE TITLE
Web root folder problems

### ISSUE THREAD

**Issue by caprenter** [Blushtones/jimdave#12]
The compressed archive of the drupal site we're working on has a `.git` directory. Git is installed on the live server and we use version control to track changes (particularly to the composer.json files as this lets you track what updates you have applied)

However, this morning when I tried to run git status on our development version... I got errors.

Further, 
* I don't see the .git directory in my containerised instance. (or any other hidden 'dot' files)
 * Git is not installed by default in the container. (but this is not a problem really)

So I think I've got 2 problems:
1) why is the .git (and other hidden files) directory not there?
(I'd like to keep/preserve the existing git history)

Answer 
I think it might be to do with how, where and when, the files are extracted.
If I do it inside the container, it seems the hidden dot files are not copied into the /var/www/<webroot> directory (!?)
But if I stop the container, then on the host machine delete the webroot directory, extract the files on the host, then spin up the container the files show up.

I googled and found this:
https://stackoverflow.com/questions/42132475/hidden-file-env-not-copied-using-docker-copy
but I don't think we are using a dockerignore file.

So this is a set up process:
We either 
a) set up the webroot files before we initialise the container
b) set them up after

2) How do we track changes in that directory via git?

a) If I run git when the webroot files are set up BEFORE container intialisation, its fine!

b) When I tried to run git status on the host machine when the files are set up AFTER the conatiner is initialised, on those files I get
`
  fatal: not a git repository (or any parent up to mount point /)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
`
I think the solutions are here: https://stackoverflow.com/questions/16853624/git-discovery-across-filesystem-not-set

I could run
`GIT_DISCOVERY_ACROSS_FILESYSTEM=1 git status`
..but that's when it complained it's not a git repo - see 1 above!

I think this is what @Plebster is suggesting a fix for in #11

**Comment by Plebster** [comment]
ok, this needs investigating.... if you look at the test server we setup on the dev server this has all hidden folders installed.

I will start a fresh install today and see what I get... yes, #11 seems to cover that too.

Does this mean our container is not fit for purpose as git is not installed in it?

**Comment by Plebster** [comment]
this should be replicable as a test... add a . file to one of your volumes, re start the compose and see if available in the container

**Comment by Plebster** [comment]
ok, I can replicate this, now to find a cure, files are visible on my host machine but not within the container

**Comment by Plebster** [comment]
ok, I think this is the solution...

all GitHub will be done on the host machine this makes one big assumption... that there will be no dotfiles involved with the drupal dev.

if we are to use GitHub then this would negate the un tarring step in the docker steps

**Comment by Plebster** [comment]
this has been addressed in #14

**Comment by Plebster** [comment]
Instructions are....
`http://wiki.jimatkinson.co.uk/index.php/Docker`
