### ISSUE TITLE
Can't install anything with composer for testing

### ISSUE THREAD

**Issue by Plebster** [Blushtones/jimdave#15]
In the /var/www/<site_folder> I can't install anything with composer to to install development tools:

composer require --dev drupal/drupal-extension:~3.0
returns a memory issue

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 167772160 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 90

re running the above with a memory pre statement
COMPOSER_MEMORY_LIMIT=-1 composer require --dev drupal/drupal-extension:~3.0
exits with a Killed statement and nothing else

both the above print EOL statements for composer1, trying to install composer 2
composer self-update --2

seems to update ok(suspiciously quickly too)

re running
composer require --dev drupal/drupal-extension:~3.0

now creates many dependency issues
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

All the above were run on a fresh instance of the development environment, little bit stuck now!!

**Comment by caprenter** [comment]
I managed to update one of the modules - first in the list.
Maybe try some things other than the module you've been trying.

**Comment by Plebster** [comment]
I'm trying to install Behat for testing... this is the only module I'm interested at the minute...

it looks like test or no testing at my knowledge limit at the minute

**Comment by Plebster** [comment]
some further investigation...

using docker1 and the command COMPOSER_MEMORY_LIMIT=-1 allocates an undefined amount of memory... I have had a little play with this
COMPOSER_MEMORY_LIMIT=2G
COMPOSER_MEMORY_LIMIT=4G
COMPOSER_MEMORY_LIMIT=8G

I have run out of memory at every time, on a newish MacBook Pro with 16Gb of RAM

I think this shows that we need to move to composer2, all the documentation I have looked at has suggested this and if possible to 2.2.0+. Get a base install, install testing and then upgrade other modules with testing in place.

[https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors](url)

**Comment by caprenter** [comment]
I'm not disagreeing, but....

Trying to upgrade an existing module might tell us if composer is working in at least once case or not.

Dev modules are, I think, quite extensive and it may be that updates are needed before a new one can be added. 

I know we've kind of decided that begat is the way to go with testing, but other options are available.

So, I'm saying all of the above because I don't think we are necessarily funneled down into one approach. 

Understanding composer 1 and 2 a bit more would definitely be good tho!

**Comment by Plebster** [comment]
Ok, I will have a look at PHPUnit installation 

this link is just here as a place holder:
[https://phpunit.de/getting-started/phpunit-7.html](url)

**Comment by caprenter** [comment]
I've had a quick play at updating some modules. (This is all within the drupal container)
Here's the low down...

drupal/auto_entitylabel       
This installed ok ( with ) but gave this warning: 
 ```
 As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
  This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives   will be lost.
  Installing 'unzip' may remediate them.
```
So I installed unzip 

drupal/colorbox               1.6.0       1.7.0       A light-weight, custom...

Installed fine.

drupal/console                1.9.5       1.9.7       The Drupal CLI. A tool...
failed because of: 
```
Package operations: 1 install, 12 updates, 1 removal
  - Removing dnoegel/php-xdg-base-dir (v0.1.1)
  - Updating symfony/polyfill-php80 (v1.18.1 => v1.23.1): Downloading (100%)         
  - Updating symfony/finder (v4.4.13 => v4.4.30):     Update failed (Failed to execute git show-ref --head -d

sh: 1: git: not found
```

So I installed git, then it updated fine.

Makes me wonder if we just need to make sure there are other packages in our docker container...

**Comment by caprenter** [comment]
UPDATE:
I've updated all the minor/point/red modules in my instance and it's gone ok.
The only database updates were in the EU Cookie Control module.
I did all this with the site in maintenance mode:
```
vendor/bin/drush state:set system.maintenance_mode 1
```
On first look and click around the site seems ok.
(obviously this is why some testing might be better!)

I have NOT done any major upgrades i.e. from 1.x to 2.x, or core up to drupal 9.

So I can get composer to do some tasks (all be it that I needed to install unzip and git)

**Comment by caprenter** [comment]
And...

I've managed to install this:
```
composer require --dev drupal/drupal-extension:~3.0
```
Whether or not this has something to do with unzip or git in the background I don't know.
Although: https://getcomposer.org/doc/00-intro.md
```
To install packages from sources instead of plain zip archives, you will need git, svn, fossil or hg depending on how the package is version-controlled.
```
I did use 
```
COMPOSER_MEMORY_LIMIT=-1
```
throughout.

BTW, I have 12GB of RAM

**Comment by Plebster** [comment]
brilliant!!!!

I have seen the zip/ issue before, git seems interesting too... if uncompressing is done using php I wonder if that is gobbling up the memory.

_To install packages from sources instead of plain zip archives, you will need git, svn, fossil or hg depending on how the package is version-controlled._

I shall concoct a docker command to run every time the container file is spun up for the above, a pain I know!!

I'll spin up a fresh instance, install the pre reqs (including nano!!) and then try to install the Drupal-extensions again

then all being well get some tests running!!! 

😃

**Comment by Plebster** [comment]
`docker exec drupal apt-get update && docker exec drupal apt-get install unzip git nano subversion fossil -y`

hg seems a bit more of a long winded install process, if it is needed I will look into it. I shall add the above to the docker instructions

**Comment by Plebster** [comment]
interestingly I'm still getting a killed message on my dirty installation

**Comment by Plebster** [comment]
No joy on a fresh install, still exits with a 'Killed' message and no debug

**Comment by caprenter** [comment]
I'll try to replicate. I wonder if this module depends on something else
being up to date.

My guess would be the devel module, or the console module.

So to confirm steps:
Clean development environment set up
Followed by try to install drupal-extension module.

Can you paste your command history somewhere for me pls?

**Comment by Plebster** [comment]
I've just tried the top two in the drupal list and they again have failed, let me tidy up my history and I'll paste

can you confirm what directory you're in when you're running these commands please?

**Comment by Plebster** [comment]
Fresh install after running 

`docker exec drupal apt-get update && docker exec drupal apt-get install unzip git nano subversion fossil -y`

2  cd /var/www/
    3  cd lamrt.org.uk/
    4  COMPOSER_MEMORY_LIMIT=-1
    5  composer require --dev drupal/drupal-extension:~3.0
    6  COMPOSER_MEMORY_LIMIT=-1 composer require --dev drupal/drupal-extension:~3.0
    7  vendor/bin/drush state:set system.maintenance_mode 1
    8  COMPOSER_MEMORY_LIMIT=-1 composer require --dev drupal/drupal-extension:~3.0
    9  composer require --dev drupal/drupal-extension:~3.0
   10  cat /usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php on line 90
   11  cat /usr/local/bin/composer/src/Composer/DependencyResolver/RuleSet.php
   12  composer show -i
   13  composer global show
   14  composer global show -i
   15  composer outdated
   16  composer require alchemy/zippy
   17  COMPOSER_MEMORY_LIMIT=-1 composer require alchemy/zippy
   18  composer outdated
   19  composer update  alchemy/zippy
   20  COMPOSER_MEMORY_LIMIT=-1 composer update alchemy/zippy
   21  COMPOSER_MEMORY_LIMIT=-1 composer update asm89/stack-cors

**Comment by Plebster** [comment]
running composer... gives memory issue
running  COMPOSER_MEMORY_LIMIT=-1 composer  gives 'Killed'

**Comment by caprenter** [comment]
That all looks fine to me. For comparison here's what I did yesterday:
```
composer outdated "drupal/*"
    3  vendor/bin/drush pm:security
    4  composer update drupal/modulename --with-dependencies
    5  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/modulename --with-dependencies
    6  composer outdated "drupal/*"
    7  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/auto_entitylabel --with-dependencies
    8  sudo apt-get update
    9  apt-get update
   10  apt-get install unzip
   11  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/colorbox --with-dependencies
   12  composer update drupal/console --with-dependencies
   13  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/console --with-dependencies
   14  apt-get install git
   15  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/console --with-dependencies
   16  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/console-core --with-dependencies
   17  composer outdated "drupal/*"
   18  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/ctools --with-dependencies
   19  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/devel --with-dependencies
   20  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/ds --with-dependencies
   21  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/eu_cookie_compliance --with-dependencies
   22  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/field_group --with-dependencies
   23  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/geofield --with-dependencies
   24  vendor/bin/drush updatedb
   25  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/geofield_map --with-dependencies
   26  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/pager_for_content_type --with-dependencies
   27  COMPOSER_MEMORY_LIMIT=-1 composer update drupal/token --with-dependencies
   28  composer outdated "drupal/*"
   29  drush updatedb
   30  vendor/bin/drush updatedb
   31  drush cache:rebuild
   32  vendor/bin/drush cache:rebuild
   33  vendor/bin/drush state:set system.maintenance_mode 0
   34  COMPOSER_MEMORY_LIMIT=-1 composer require --dev drupal/drupal-extension:~3.0
```
