### ISSUE TITLE
Wiki: Setting up image test

### ISSUE THREAD

**Issue by caprenter** [Blushtones/jimdave#19]
On the TESTING page of the wiki:

This failed for me (on our vanilla drupal 8.9.5 project install):

>   Open the file features/bootstrap/FeatureContext.php
> 
>   Add the following two lines under the use list at the top
> 
>   u se Behat\Behat\Tester\Exception\PendingException; NB THIS IS ALREADY PRESENT IN DAVE'S COPY
>   use Behat\MinkExtension\Context\MinkContext;

As you can see from my edit - Pending Exception was already present, and there's an error because MinkExtension is already declared in behat.yml

My fix was to comment out the Mink Extension line in **behat.yml** - removing it from FeatureContext.php did not work.
```
default:
  suites:
    my_suite:
      contexts:
        - FeatureContext
        #- Behat\MinkExtension\Context\MinkContext
  extensions:
    Behat\MinkExtension:
      base_url:  'http://www.lamrt.org.uk'
      sessions:
        default:
          goutte: ~
``

**Comment by Plebster** [comment]
yes, this is a typo.... removing it from the behat.yml is the correct approach... oops :)

**Comment by Plebster** [comment]
so, prob not a typo per say... I just missed a step when going from the basic testing to a slightly more complex test. the wiki has been updated
