### ISSUE TITLE
Drupal 9 version

### ISSUE THREAD

**Issue by caprenter** [Blushtones/jimdave#21]
Create a Drupal 9 version

**Comment by caprenter** [comment]
see https://github.com/Blushtones/jimdave/commit/9aaf405836bd88aa3f8ca621001427af1a181e80

**Comment by Plebster** [comment]
this needs some playing with and deciding which version to use... interestingly I don't get the latest version of drupal when either leaving it blank(on a fresh instance) or by using the drupal:latest tag

**Comment by caprenter** [comment]
I think the docker image is coming down as the latest (?), but the composer file we use to update is locked at a lower version.
That's my explanation for now at least!

**Comment by caprenter** [comment]
I think we're on top of this now so closing this issue. The understanding above is correct and we're looking to peg our builds to specific versions
