### ISSUE TITLE
Live docker-compose

### ISSUE THREAD

**Issue by Plebster** [Blushtones/jimdave#25]
a live version of docker-compose is required

remove phpmyadmin, this can be easily spun up if required

link mysql and drupal container limiting ports that are 'visable'

**Comment by Plebster** [comment]
Also 443 port maybe required for ssl

**Comment by caprenter** [comment]
You've put a version on the wiki. It would be good to have a file in this repo - one that we know works and won't need to be copy and pasted.

(Can it be docker-compose.live.yaml - we rename it on deployment - I think that is better than a live branch for example)

We are planning on setting up/moving the letsencrypt certificates, I suspect we will want port 443 available.
