### ISSUE TITLE
Composer workflow issues

### ISSUE THREAD

**Issue by caprenter** [Blushtones/jimdave#8]
Started to look at updates using composer.

Some notes:

to run the Drush commands from the web root, prepend with

`  vendor/bin/`

e.g. 

`  vendor/bin/drush state:set system.maintenance_mode 1`

Using Composer.
It suggests you update to version 2
https://blog.packagist.com/composer-2-0-is-now-available/

When I did that I got plugin errors

Without upgrading to 2 I get php memory limit errors.
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

 I have updated one module using

`COMPOSER_MEMORY_LIMIT=-1 composer update drupal/<module name> --with-dependencies`
  
So it needs a bit of troubleshooting and maybe container wrangling?

**Comment by Plebster** [comment]
@caprenter, Sorry, I seem to have completely hijacked this in #15 can we merge issues?

**Comment by caprenter** [comment]
You can't really merge issues, but you can reference them (as you are
doing).
Also copy and paste info over, close as duplicates etc. Whatever works to
keep it tidy and maintain info

**Comment by caprenter** [comment]
Closing as this has been dealt with. How to use Composer is now on our wiki
