### ISSUE TITLE
Boot Sequence of Docker-compose

### ISSUE THREAD

**Issue by Plebster** [Blushtones/jimdave#9]
Added depends_on to the docker-compose file...

sequence should be database up and running, then drupal/ phpmyadmin

**Comment by caprenter** [comment]
Running on Ubuntu 20.04 I had the error:

ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.drupal.depends_on contains an invalid type, it should be an array, or >
services.phpmyadmin.depends_on contains an invalid type, it should be an array,>

Fix coming..

**Comment by caprenter** [comment]
@Plebster  this works for me now. Can you test to make sure it's not broken for you please?
I used this to get some background on my error:
https://github.com/moby/moby/issues/30404

**Comment by Plebster** [comment]
Grrr, I thought I'd pushed this back up to git. the format should be:

    depends_on:
      - db

I'll amend this today

**Comment by Plebster** [comment]
all fixed
